version: '1'

networks:
  asp-dotnet-network:
    driver: bridge

services:

  # nginx:
  #   build:
  #     context: ./NewsAggregator.Angular
  #     dockerfile: Dockerfile
  #   container_name: ContainerNginxAngular
  #   # volumes:
  #   #   - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - asp-dotnet-network
      
  # angular:
  #   build:
  #     context: ./NewsAggregator.Angular
  #     dockerfile: Dockerfile
  #   container_name: Container Angular 
  #   ports:
  #     - "4200:4200"
  #   networks:
  #     - asp-dotnet-network
  #   depends_on:
  #     - api

  backend:
    restart: always
    build:
      context: ./NewsAggregator.API
      dockerfile: Dockerfile
    container_name: ContainerAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    networks:
      - asp-dotnet-network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: ContainerPostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MirtekNewsAggregation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - asp-dotnet-network
volumes:
 postgres_data:


