version: '1'

networks:
  asp-dotnet-network:
    driver: bridge

services:

  angular:
    image: angular:latest
    build:
      context: ./NewsAggregator.Angular
      dockerfile: Dockerfile
    container_name: ContainerAngular
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - asp-dotnet-network
      
  api:
    restart: always
    build:
      context: ./NewsAggregator.API
      dockerfile: Dockerfile
    container_name: ContainerAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    networks:
      - asp-dotnet-network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: ContainerPostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MirtekNewsAggregation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - asp-dotnet-network
volumes:
 postgres_data:


